# Configuration for the preprocessing script
input_file: "data/raw/pg345.txt"  # Path to the raw text file
output_file: "data/processed/dracula_cleaned.txt"  # Path to save the cleaned text file

# Preprocessing settings
cleaning:
  remove_metadata: false
  split_by_chapters: true
  remove_special_characters: false
  lower_case: true
  split_paragraphs: true

# Tokenization settings
tokenization:
  max_length: 512  # Max token length for model training
  batch_size: 8    # Batch size for tokenization
